/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fixent.publish.client.notification.view;


/**
 *
 * @author Mathan
 */
public class NotificationView extends javax.swing.JPanel {

    /**
     * Creates new form BookListView
     */
    public NotificationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        notificationTable = new javax.swing.JTable();
        printButton = new javax.swing.JButton();
        printAllButton = new javax.swing.JButton();
        notificationLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        notificationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        notificationTable.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(notificationTable);

        printButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        printButton.setText("Print ");

        printAllButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        printAllButton.setText("Print All");

        notificationLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        notificationLabel.setText("Notifications");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notificationLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(printAllButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(printButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(notificationLabel)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(printButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printAllButton)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel notificationLabel;
    private javax.swing.JTable notificationTable;
    private javax.swing.JButton printAllButton;
    private javax.swing.JButton printButton;
    // End of variables declaration//GEN-END:variables
	public javax.swing.JLabel getNotificationLabel() {
		return notificationLabel;
	}

	public void setNotificationLabel(javax.swing.JLabel jLabel1) {
		this.notificationLabel = jLabel1;
	}

	public javax.swing.JScrollPane getjScrollPane1() {
		return jScrollPane1;
	}

	public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
		this.jScrollPane1 = jScrollPane1;
	}

	public javax.swing.JTable getNotificationTable() {
		return notificationTable;
	}

	public void setNotificationTable(javax.swing.JTable notificationTable) {
		this.notificationTable = notificationTable;
	}

	public javax.swing.JButton getPrintAllButton() {
		return printAllButton;
	}

	public void setPrintAllButton(javax.swing.JButton printAllButton) {
		this.printAllButton = printAllButton;
	}

	public javax.swing.JButton getPrintButton() {
		return printButton;
	}

	public void setPrintButton(javax.swing.JButton printButton) {
		this.printButton = printButton;
	}

}
