/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fixent.publish.client.common;

/**
 *
 * @author Mathan
 */
public class LeftPanel extends javax.swing.JPanel {

    /**
     * Creates new form LeftPanel
     */
    public LeftPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookInfoButton = new javax.swing.JButton();
        bookSubscribeButton = new javax.swing.JButton();
        publishEditionButton = new javax.swing.JButton();
        notificationButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bookInfoButton.setBackground(new java.awt.Color(61, 86, 109));
        bookInfoButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        bookInfoButton.setForeground(new java.awt.Color(255, 255, 255));
        bookInfoButton.setText("Book");
        bookInfoButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        bookInfoButton.setFocusPainted(false);

        bookSubscribeButton.setBackground(new java.awt.Color(61, 86, 109));
        bookSubscribeButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        bookSubscribeButton.setForeground(new java.awt.Color(255, 255, 255));
        bookSubscribeButton.setText("Subscription");
        bookSubscribeButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        bookSubscribeButton.setFocusPainted(false);
        bookSubscribeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSubscribeButtonActionPerformed(evt);
            }
        });

        publishEditionButton.setBackground(new java.awt.Color(61, 86, 109));
        publishEditionButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        publishEditionButton.setForeground(new java.awt.Color(255, 255, 255));
        publishEditionButton.setText("Book Publish");
        publishEditionButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        publishEditionButton.setFocusPainted(false);

        notificationButton.setBackground(new java.awt.Color(61, 86, 109));
        notificationButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        notificationButton.setForeground(new java.awt.Color(255, 255, 255));
        notificationButton.setText("Search");
        notificationButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        notificationButton.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookSubscribeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(publishEditionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(notificationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bookInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bookSubscribeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(publishEditionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(notificationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookSubscribeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSubscribeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookSubscribeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookInfoButton;
    private javax.swing.JButton bookSubscribeButton;
    private javax.swing.JButton notificationButton;
    private javax.swing.JButton publishEditionButton;
    // End of variables declaration//GEN-END:variables
	public javax.swing.JButton getBookButton() {
		return bookInfoButton;
	}

	public void setBookButton(javax.swing.JButton bookButton) {
		this.bookInfoButton = bookButton;
	}

	public javax.swing.JButton getDeliveryButton() {
		return publishEditionButton;
	}

	public void setDeliveryButton(javax.swing.JButton deliveryButton) {
		this.publishEditionButton = deliveryButton;
	}

	public javax.swing.JButton getNotificationButton() {
		return notificationButton;
	}

	public void setNotificationButton(javax.swing.JButton notificationButton) {
		this.notificationButton = notificationButton;
	}

	public javax.swing.JButton getSubscriberButton() {
		return bookSubscribeButton;
	}

	public void setSubscriberButton(javax.swing.JButton subscriberButton) {
		this.bookSubscribeButton = subscriberButton;
	}

	public javax.swing.JButton getBookInfoButton() {
		return bookInfoButton;
	}

	public void setBookInfoButton(javax.swing.JButton bookInfoButton) {
		this.bookInfoButton = bookInfoButton;
	}

	public javax.swing.JButton getBookSubscribeButton() {
		return bookSubscribeButton;
	}

	public void setBookSubscribeButton(javax.swing.JButton bookSubscribeButton) {
		this.bookSubscribeButton = bookSubscribeButton;
	}

	public javax.swing.JButton getPublishEditionButton() {
		return publishEditionButton;
	}

	public void setPublishEditionButton(javax.swing.JButton publishEditionButton) {
		this.publishEditionButton = publishEditionButton;
	}
    
}
